export type ContentKind = "blog" | "conhecimento" | "case";
export type ContentItem = { kind: ContentKind; slug: string; title: string; excerpt: string; category: string; readTime: string; date: string; body: string[]; faqs: { question: string; answer: string }[]; };
export type GlossaryItem = { slug: string; term: string; definition: string; category: string; body: string[]; related: string[]; };

export const contentItems: ContentItem[] = [
{ kind:"blog",slug:"pmo-que-influencia-decisoes",title:"O PMO que influencia decisões não começa pelo dashboard",excerpt:"Antes da ferramenta, um PMO relevante cria linguagem comum para priorizar, decidir e acompanhar valor.",category:"PMO Estratégico",readTime:"7 min",date:"12 jun 2026",body:["Um PMO não se torna estratégico por estar próximo da diretoria. Ele se torna estratégico quando melhora a qualidade das decisões que chegam à diretoria.","O ponto de partida é identificar quais decisões precisam de mais clareza. Priorização, capacidade, risco e benefícios são algumas delas. A partir daí, o escritório organiza ritos, evidências e responsabilidades.","O dashboard entra depois. Ele é consequência de uma governança que já sabe o que precisa enxergar — e para quê."],faqs:[{question:"Quando um PMO precisa ser redesenhado?",answer:"Quando os reportes não mudam decisões, as prioridades se alteram sem critério ou a liderança não enxerga valor na atuação do escritório."},{question:"Todo PMO precisa ser estratégico?",answer:"Não. O modelo deve responder à maturidade e aos desafios reais da organização. Estratégia é relevância para a decisão, não um rótulo."}]},
{ kind:"blog",slug:"okrs-sem-teatro-de-alinhamento",title:"OKRs sem teatro de alinhamento: como manter o foco no que muda",excerpt:"Objetivos só ganham força quando provocam escolhas. O resto é lista de desejos bem diagramada.",category:"OKRs",readTime:"6 min",date:"28 mai 2026",body:["OKRs funcionam quando ajudam a organização a dizer não. Sem escolhas explícitas, objetivos viram uma nova camada de acompanhamento sobre a rotina existente.","A boa prática é conectar resultados-chave a evidências observáveis e revisá-los em uma cadência que permita correção de rota.","O objetivo não é preencher uma plataforma. É criar foco coletivo para uma mudança relevante."],faqs:[{question:"Qual é a cadência recomendada?",answer:"Em geral, trimestral para revisão de objetivos e semanal ou quinzenal para acompanhamento de sinais e impedimentos."},{question:"OKRs substituem indicadores operacionais?",answer:"Não. OKRs orientam mudanças prioritárias; indicadores operacionais mantêm a saúde da rotina visível."}]},
{ kind:"blog",slug:"governanca-que-decide",title:"Governança não é reunião: é decisão com responsabilidade clara",excerpt:"A diferença entre uma rotina de governança e uma agenda cheia está no que muda depois de cada encontro.",category:"Governança",readTime:"5 min",date:"08 mai 2026",body:["Governança existe para reduzir ambiguidade. Cada rito precisa deixar claro quem decide, com qual evidência e como o próximo passo será acompanhado.","Quando a reunião apenas atualiza status, ela consome energia sem alterar o rumo da execução.","Uma rotina bem desenhada separa informação, discussão e decisão. Essa distinção parece simples, mas muda a qualidade da cadência."],faqs:[{question:"Quantos ritos de governança uma empresa precisa?",answer:"Apenas os necessários para as decisões críticas. O desenho deve reduzir, não aumentar, a burocracia."},{question:"Governança reduz autonomia?",answer:"Boa governança cria limites claros para que as pessoas possam agir com mais autonomia e menos retrabalho."}]},
{ kind:"conhecimento",slug:"guia-maturidade-pmo",title:"Guia de maturidade de PMO: cinco perguntas para começar",excerpt:"Um roteiro objetivo para entender se o escritório de projetos apoia execução ou apenas reporta status.",category:"Guia técnico",readTime:"12 min",date:"04 jun 2026",body:["Maturidade não é quantidade de processos. É a capacidade de tomar melhores decisões de forma consistente.","Comece perguntando: quais decisões o PMO apoia, que dados tornam essas decisões mais claras e o que acontece depois de cada rito?","O diagnóstico deve revelar lacunas de governança, informação, capacidade e comportamento — sem confundir atividade com impacto."],faqs:[{question:"O diagnóstico exige ferramentas específicas?",answer:"Não. Entrevistas, análise de ritos e leitura de portfólio já revelam padrões importantes."},{question:"Quanto tempo leva?",answer:"Uma leitura inicial pode ser feita em poucas semanas, dependendo do porte e da disponibilidade da organização."}]},
{ kind:"conhecimento",slug:"matriz-priorizacao-portfolio",title:"Matriz de priorização de portfólio",excerpt:"Um material prático para comparar iniciativas por valor, esforço, risco e alinhamento estratégico.",category:"Material prático",readTime:"9 min",date:"18 mai 2026",body:["Priorizar é comparar. Quando os critérios não são explícitos, a agenda mais urgente costuma vencer a mais importante.","Uma boa matriz combina valor esperado, esforço, risco e alinhamento estratégico. Mais importante que a fórmula é a conversa que ela organiza.","Use a matriz como instrumento de decisão, não como substituto da responsabilidade executiva."],faqs:[{question:"Quem deve participar da priorização?",answer:"Quem responde pela estratégia, pela capacidade de execução e pelos resultados do portfólio."},{question:"A matriz resolve conflitos?",answer:"Ela torna os critérios visíveis. O conflito saudável continua sendo uma decisão de liderança."}]},
{ kind:"case",slug:"governanca-portfolio-industria",title:"Governança de portfólio para reduzir dispersão em uma indústria",excerpt:"Uma nova cadência de decisão trouxe foco às iniciativas e clareza para a liderança sobre capacidade e risco.",category:"Indústria",readTime:"Caso",date:"2026",body:["O desafio não era falta de iniciativas. Era excesso de movimentos paralelos, com dependências pouco visíveis e critérios inconsistentes de priorização.","A atuação começou pelo mapa de decisões e pela leitura do portfólio. Em seguida, foram definidos ritos executivos, critérios comuns e um fluxo de escalonamento.","O resultado foi uma conversa de portfólio mais objetiva, com menos retrabalho e maior transparência sobre o que cabia na capacidade disponível."],faqs:[{question:"Que tipo de organização se beneficia desse modelo?",answer:"Empresas com múltiplas iniciativas concorrendo por recursos e pouca visibilidade de dependências."},{question:"O trabalho substitui a liderança interna?",answer:"Não. A consultoria estrutura o método para que a liderança tome decisões com mais clareza."}]},
{ kind:"case",slug:"vmo-servicos-financeiros",title:"Do controle de contratos à gestão de valor em serviços financeiros",excerpt:"Uma estrutura de VMO integrou fornecedores, benefícios e prioridades em uma mesma conversa executiva.",category:"Serviços financeiros",readTime:"Caso",date:"2026",body:["A organização precisava ir além do controle de custos. Contratos relevantes estavam ativos, mas os resultados esperados não eram acompanhados de forma comparável.","O trabalho estruturou critérios de valor, papéis de decisão e uma visão integrada de benefícios, riscos e compromissos dos fornecedores.","Com o modelo, líderes passaram a discutir escolhas de investimento com uma linguagem comum e um caminho mais claro para escalar decisões."],faqs:[{question:"VMO é apenas para grandes empresas?",answer:"Não. O modelo pode começar simples, desde que responda a uma decisão real sobre investimento e valor."},{question:"Por onde começa uma implantação?",answer:"Pelo entendimento do portfólio de decisões, investimentos e resultados que a organização precisa tornar visíveis."}]},
{ kind:"case",slug:"agilidade-operacao-tecnologia",title:"Cadência ágil para recuperar previsibilidade em uma operação de tecnologia",excerpt:"Ritos mais claros e trabalho visual reduziram ruídos entre prioridades estratégicas e times de entrega.",category:"Tecnologia",readTime:"Caso",date:"2026",body:["A operação tinha equipes comprometidas, mas muitas interrupções e pouca clareza sobre o que realmente deveria avançar em cada ciclo.","A intervenção reorganizou o fluxo de priorização, os acordos de trabalho e os ritos de revisão, conectando liderança e times em torno de evidências simples.","A principal mudança não foi adotar um novo vocabulário ágil. Foi tornar o trabalho mais visível e a tomada de decisão mais próxima da execução."],faqs:[{question:"Metodologias ágeis funcionam fora de tecnologia?",answer:"Sim. Os princípios de ciclos curtos, transparência e aprendizado podem ser adaptados a diferentes contextos."},{question:"O que vem antes: ferramenta ou rito?",answer:"Rito e decisão. A ferramenta deve apoiar uma forma de trabalho já compreendida pelas pessoas."}]}
];

export const glossary: GlossaryItem[] = [
{slug:"governanca",term:"Governança",category:"Estratégia",definition:"Conjunto de decisões, responsabilidades e ritos que orienta uma organização a agir com coerência.",body:["Governança define como escolhas relevantes são feitas, registradas e acompanhadas. Ela não é uma camada extra de burocracia: é a estrutura que evita que decisões críticas fiquem implícitas.","Uma governança útil deixa claro quem decide, quais evidências são necessárias e quando um tema deve ser escalonado."],related:["PMO","Portfólio"]},
{slug:"okr",term:"OKR",category:"Estratégia",definition:"Objetivos e resultados-chave que tornam uma mudança prioritária explícita e acompanhável.",body:["OKR é a sigla para Objectives and Key Results. O objetivo descreve a mudança desejada; os resultados-chave mostram, com evidência, se ela está acontecendo.","O método funciona melhor quando traz escolhas para a superfície e quando a cadência de revisão permite aprender antes do fim do ciclo."],related:["Governança","Portfólio"]},
{slug:"pmo",term:"PMO",category:"Execução",definition:"Escritório de projetos que pode apoiar padrões, execução, portfólio e decisões.",body:["PMO significa Project Management Office. Sua função não é fixa: pode ser mais operacional, tática ou estratégica, conforme os desafios da organização.","Um PMO relevante organiza informação para que líderes e times tomem decisões melhores sobre prioridades, riscos, capacidade e benefícios."],related:["Governança","VMO"]},
{slug:"portfolio",term:"Portfólio",category:"Execução",definition:"Conjunto de iniciativas que disputa recursos e deve ser gerido como uma escolha estratégica.",body:["Portfólio não é uma lista de projetos. É o conjunto de apostas que compartilha pessoas, orçamento, atenção da liderança e capacidade de entrega.","A gestão de portfólio torna as escolhas explícitas: o que inicia, o que continua, o que pausa e o que deixa de fazer sentido."],related:["PMO","OKR"]},
{slug:"vmo",term:"VMO",category:"Valor",definition:"Value Management Office: estrutura que conecta investimentos, iniciativas e fornecedores ao valor entregue.",body:["VMO é uma estrutura voltada a tornar o valor visível ao longo de investimentos e parcerias. Ela integra benefícios, resultados, riscos e decisões de priorização.","O foco não é apenas controlar contratos ou custos. É entender se o investimento está contribuindo para a mudança que a estratégia precisa gerar."],related:["PMO","Governança"]}
];
export const categories = ["Todos", "PMO Estratégico", "OKRs", "Governança", "Guia técnico", "Material prático", "Indústria", "Serviços financeiros", "Tecnologia"];
