import { ArrowLeft, ArrowUpRight, Check, ChevronRight, Clock3, Layers3 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import LeadChat from "@/components/LeadChat";

type PageData = { type: "Solução" | "Treinamento"; eyebrow: string; title: string; intro: string; image: string; outcome: string; points: string[]; related: string[] };

const pages: Record<string, PageData> = {
  "governanca-pmo": { type: "Solução", eyebrow: "Governança orientada a resultados", title: "Governança & PMO que conectam estratégia e entrega.", intro: "Estruturamos decisões, ritos e visibilidade para que o portfólio avance com direção clara.", image: "/assets/governanca-pmo.png", outcome: "Mais clareza sobre prioridades, decisões mais rápidas e uma cadência confiável para a execução.", points: ["Diagnóstico de maturidade e governança", "Modelo de PMO alinhado ao contexto", "Ritos, indicadores e reportes executivos", "Gestão integrada de portfólio e prioridades"], related: ["Estratégia distante da execução", "Portfólio sem priorização clara"] },
  "vmo-valor": { type: "Solução", eyebrow: "Value Management Office", title: "VMO para tornar valor uma prática visível.", intro: "Conectamos investimentos, fornecedores e iniciativas às prioridades que realmente movem o negócio.", image: "/assets/vmo-valor.png", outcome: "Uma visão comum sobre valor, com decisões apoiadas por evidências e impacto mensurável.", points: ["Desenho de modelo operacional de VMO", "Gestão de valor e benefícios", "Governança de fornecedores", "Priorização dinâmica de iniciativas"], related: ["Fornecedores sem gestão de valor", "PMO sem influência nas decisões"] },
  "educacao-executiva": { type: "Solução", eyebrow: "Capacitação aplicada", title: "Educação executiva que continua na operação.", intro: "Desenvolvemos líderes e times para traduzirem método em uma nova forma de decidir e entregar.", image: "/assets/educacao-executiva.png", outcome: "Capacidades que permanecem: times mais preparados para agir com autonomia, alinhamento e foco.", points: ["Programas para liderança e times", "Gestão de projetos e métodos ágeis", "OKRs e gestão de valor", "Aprendizado conectado a desafios reais"], related: ["Baixa maturidade de PMO", "Estratégia distante da execução"] },
  "governanca-estrategica-okrs": { type: "Treinamento", eyebrow: "Programa · 06 etapas", title: "Governança Estratégica: da Gestão de Projetos aos OKRs", intro: "Uma abordagem prática para aprimorar a gestão de projetos e alinhar objetivos, resultados e operações.", image: "/assets/governanca-pmo.png", outcome: "Ao final, os participantes podem transformar prioridades estratégicas em uma cadência de execução clara.", points: ["Projetos e objetivos em uma mesma direção", "OKRs aplicados à realidade da operação", "Ritos de acompanhamento e decisão", "Indicadores que orientam a ação"], related: ["Para lideranças, PMOs e gestores de portfólio", "Formato sob medida para sua organização"] },
  "transformacao-pmo-vmo": { type: "Treinamento", eyebrow: "Programa · 06 etapas", title: "Transformação Organizacional: de PMO ao VMO", intro: "Para executivos e gestores que desejam evoluir a gestão estratégica e ampliar o valor percebido da entrega.", image: "/assets/vmo-valor.png", outcome: "Uma visão prática para redesenhar a atuação do PMO e criar uma governança orientada a valor real.", points: ["Evolução do PMO para VMO", "Priorização e governança de valor", "Alinhamento de estratégia e operação", "Métricas de impacto e resultados"], related: ["Para executivos e gerentes", "Formato sob medida para sua organização"] },
  "metodologias-ageis": { type: "Treinamento", eyebrow: "Programa · 06 etapas", title: "Excelência Operacional com Metodologias Ágeis", intro: "Práticas ágeis para criar colaboração, foco e melhoria contínua em contextos de alta complexidade.", image: "/assets/educacao-executiva.png", outcome: "Participantes preparados para aplicar métodos ágeis e sustentar melhorias na rotina de seus projetos.", points: ["Fundamentos de agilidade aplicada", "Trabalho em sprint e ciclos de gestão", "Alinhamento de times e prioridades", "Retrospectivas e melhoria contínua"], related: ["Para lideranças e equipes", "Formato sob medida para sua organização"] },
};

const DetailPage = () => {
  const { slug } = useParams();
  const page = slug ? pages[slug] : undefined;
  if (!page) return <div className="grid min-h-screen place-items-center bg-[#f3eee1]"><Link to="/" className="font-outfit text-sm underline">Voltar para a Lucinari</Link></div>;
  const contactLabel = page.type === "Treinamento" ? "Quero participar deste treinamento" : "Quero conversar sobre esta solução";
  return <main className="min-h-screen bg-[#f3eee1] text-[#0e302e]"><header className="bg-[#0e302e] px-6 py-5 lg:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between"><Link to="/" className="font-fraunces text-xl text-white">lucinari<span className="text-[#e2c88c]">.</span><span className="ml-2 font-outfit text-[9px] uppercase tracking-[.24em] text-white/60">consulting</span></Link><Link to="/" className="flex items-center gap-2 font-outfit text-[10px] font-bold uppercase tracking-widest text-[#e2c88c]"><ArrowLeft size={14}/> Início</Link></div></header>
    <section className="bg-[#0e302e] px-6 pb-20 pt-14 text-white lg:px-10 lg:pb-28"><div className="mx-auto grid max-w-7xl items-end gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="font-outfit text-[11px] font-bold uppercase tracking-[.22em] text-[#e2c88c]">{page.type} · {page.eyebrow}</p><h1 className="mt-5 font-fraunces text-5xl leading-[.98] lg:text-7xl">{page.title}</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-white/70">{page.intro}</p></div><img className="aspect-[4/3] w-full rounded-[1.8rem] object-cover" src={page.image} alt=""/></div></section>
    <section className="px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-outfit text-[11px] font-bold uppercase tracking-[.2em] text-[#a07c3a]">O que muda</p><h2 className="mt-4 font-fraunces text-4xl leading-tight">{page.outcome}</h2><button onClick={() => window.dispatchEvent(new Event("open-lucinari-chat"))} className="mt-8 rounded-full bg-[#0e302e] px-6 py-3.5 font-outfit text-xs font-bold uppercase tracking-wider text-white">{contactLabel}</button></div><div className="grid gap-3">{page.points.map((point, index) => <div key={point} className="flex items-center gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#f3eee1] font-outfit text-xs text-[#a07c3a]">0{index + 1}</span><p className="font-fraunces text-xl">{point}</p><Check className="ml-auto text-[#a07c3a]" size={18}/></div>)}</div></div></section>
    <section className="bg-[#1e514a] px-6 py-16 text-white lg:px-10"><div className="mx-auto max-w-7xl"><p className="font-outfit text-[11px] font-bold uppercase tracking-[.2em] text-[#e2c88c]">Para o seu contexto</p><div className="mt-7 grid gap-4 md:grid-cols-2">{page.related.map((item) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-white/15 p-5"><Layers3 className="text-[#e2c88c]" size={20}/><p className="font-fraunces text-xl">{item}</p><ChevronRight className="ml-auto text-[#e2c88c]"/></div>)}</div></div></section>
    <section className="bg-[#fffdf8] px-6 py-20 text-center lg:px-10"><Clock3 className="mx-auto text-[#a07c3a]" size={24}/><h2 className="mx-auto mt-5 max-w-2xl font-fraunces text-4xl">Toda transformação começa ao revelar o próximo passo.</h2><button onClick={() => window.dispatchEvent(new Event("open-lucinari-chat"))} className="mt-8 rounded-full bg-[#c7a45b] px-6 py-3.5 font-outfit text-xs font-bold uppercase tracking-wider text-[#0e302e]">Falar com especialista <ArrowUpRight className="ml-1 inline" size={15}/></button></section>
    <LeadChat contextualInterest={page.title} />
  </main>;
};

export default DetailPage;
