import { ArrowUpRight, Check, ChevronRight, Layers3 } from "lucide-react";
import { Link, useParams } from "react-router-dom";

type PageData = { type: "Solução" | "Treinamento"; eyebrow: string; title: string; intro: string; image: string; outcome: string; points: string[]; related: string[] };
const pages: Record<string, PageData> = {
  "governanca-pmo": { type: "Solução", eyebrow: "Governança orientada a resultados", title: "Governança & PMO que conectam estratégia e entrega.", intro: "Estruturamos decisões, ritos e visibilidade para que o portfólio avance com direção clara.", image: "/assets/governanca-pmo.png", outcome: "Mais clareza sobre prioridades, decisões mais rápidas e uma cadência confiável.", points: ["Diagnóstico de maturidade", "Modelo de PMO", "Ritos e indicadores", "Gestão de portfólio"], related: ["Estratégia distante da execução", "Portfólio sem priorização clara"] },
  "vmo-valor": { type: "Solução", eyebrow: "Value Management Office", title: "VMO para tornar valor uma prática visível.", intro: "Conectamos investimentos, fornecedores e iniciativas às prioridades que movem o negócio.", image: "/assets/vmo-valor.png", outcome: "Decisões apoiadas por evidências e impacto mensurável.", points: ["Modelo operacional de VMO", "Gestão de benefícios", "Governança de fornecedores", "Priorização dinâmica"], related: ["Fornecedores sem gestão de valor", "PMO sem influência nas decisões"] },
  "educacao-executiva": { type: "Solução", eyebrow: "Capacitação aplicada", title: "Educação executiva que continua na operação.", intro: "Desenvolvemos líderes e times para traduzirem método em uma nova forma de decidir e entregar.", image: "/assets/educacao-executiva.png", outcome: "Capacidades que permanecem em times mais autônomos e alinhados.", points: ["Programas para liderança", "Métodos ágeis", "OKRs e valor", "Aprendizado aplicado"], related: ["Baixa maturidade de PMO", "Estratégia distante da execução"] },
  "governanca-estrategica-okrs": { type: "Treinamento", eyebrow: "Programa · 06 etapas", title: "Governança Estratégica: da Gestão de Projetos aos OKRs", intro: "Uma abordagem prática para alinhar objetivos, resultados e operações.", image: "/assets/governanca-pmo.png", outcome: "Prioridades estratégicas traduzidas em cadência clara de execução.", points: ["Projetos e objetivos", "OKRs aplicados", "Ritos de decisão", "Indicadores"], related: ["Para lideranças e PMOs", "Formato sob medida"] },
  "transformacao-pmo-vmo": { type: "Treinamento", eyebrow: "Programa · 06 etapas", title: "Transformação Organizacional: de PMO ao VMO", intro: "Para executivos que desejam evoluir a gestão estratégica e ampliar valor percebido.", image: "/assets/vmo-valor.png", outcome: "Uma visão prática para redesenhar a atuação do PMO.", points: ["Evolução PMO para VMO", "Priorização", "Alinhamento", "Métricas de impacto"], related: ["Para executivos", "Formato sob medida"] },
  "metodologias-ageis": { type: "Treinamento", eyebrow: "Programa · 06 etapas", title: "Excelência Operacional com Metodologias Ágeis", intro: "Práticas ágeis para criar colaboração, foco e melhoria contínua.", image: "/assets/educacao-executiva.png", outcome: "Participantes preparados para sustentar melhorias nos projetos.", points: ["Agilidade aplicada", "Ciclos de gestão", "Times e prioridades", "Melhoria contínua"], related: ["Para liderança e equipes", "Formato sob medida"] },
};
const DetailPage = () => { const { slug } = useParams(); const page = slug ? pages[slug] : undefined; if (!page) return <main className="grid min-h-[60vh] place-items-center bg-[#f3eee1]"><Link to="/">Voltar ao início</Link></main>; return <main className="bg-[#f3eee1]"><section className="bg-[#0e302e] px-6 py-20 text-white lg:px-10 lg:py-28"><div className="mx-auto grid max-w-7xl items-end gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="font-outfit text-[11px] font-bold uppercase tracking-[.2em] text-[#e2c88c]">{page.type} · {page.eyebrow}</p><h1 className="mt-5 font-fraunces text-5xl leading-[.96] lg:text-7xl">{page.title}</h1><p className="mt-7 text-lg leading-relaxed text-white/70">{page.intro}</p></div><img src={page.image} className="aspect-[4/3] rounded-[1.8rem] object-cover" alt=""/></div></section><section className="px-6 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="font-outfit text-[11px] font-bold uppercase tracking-[.2em] text-[#a07c3a]">O que muda</p><h2 className="mt-4 font-fraunces text-4xl">{page.outcome}</h2><button onClick={() => window.dispatchEvent(new Event("open-lucinari-chat"))} className="mt-8 rounded-full bg-[#0e302e] px-6 py-3.5 font-outfit text-xs font-bold uppercase tracking-wider text-white">Falar com especialista</button></div><div className="grid gap-3">{page.points.map((item, i) => <div className="flex items-center gap-4 rounded-2xl bg-white p-5" key={item}><span className="font-outfit text-[#a07c3a]">0{i + 1}</span><p className="font-fraunces text-xl">{item}</p><Check className="ml-auto text-[#a07c3a]" size={18}/></div>)}</div></div></section><section className="bg-[#1e514a] px-6 py-16 text-white lg:px-10"><div className="mx-auto max-w-7xl grid gap-4 md:grid-cols-2">{page.related.map((item) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-white/15 p-5"><Layers3 className="text-[#e2c88c]"/><span className="font-fraunces text-xl">{item}</span><ChevronRight className="ml-auto text-[#e2c88c]"/></div>)}</div></section></main>; };
export default DetailPage;
