import { ChevronDown, Menu, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";

export const Header = () => {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-40 border-b border-white/10 bg-[#0e302e]/95 text-white backdrop-blur"><nav className="mx-auto flex h-[80px] max-w-7xl items-center justify-between px-5 lg:px-10"><Link to="/" className="flex items-center" aria-label="Lucinari Consulting — Página inicial"><img src="/assets/Lucinari-consulting-logo-horizontal-sem-fundo.png" alt="Lucinari Consulting" className="h-12 w-auto object-contain lg:h-16"/></Link><div className="hidden items-center gap-6 font-outfit text-[10px] font-semibold uppercase tracking-[.12em] text-white/75 lg:flex"><div className="group relative py-7"><span className="flex cursor-default items-center gap-1 text-white transition group-hover:text-[#e2c88c]">PRODUTOS <ChevronDown size={14} className="transition group-hover:rotate-180"/></span><div className="pointer-events-none absolute left-0 top-[67px] w-80 translate-y-2 rounded-2xl border border-white/10 bg-[#123c38] p-2 opacity-0 shadow-2xl transition duration-200 group-hover:pointer-events-auto group-hover:translate-y-0 group-hover:opacity-100"><p className="px-4 py-2 text-[9px] tracking-[.18em] text-[#e2c88c]">PRODUTOS & SERVIÇOS</p><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/solucoes/governanca-gestao-projetos">Governança & Gestão de Projetos</Link><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/solucoes/estruturacao-pmo-vmo">Escritório de Projetos (PMO / VMO)</Link><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/solucoes/gestao-agil">Gestão Ágil</Link><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/solucoes/educacao-executiva">Educação Executiva</Link></div></div><Link to="/sobre">Sobre</Link><Link to="/blog">Blog</Link><Link to="/conhecimentos">Conhecimentos</Link><Link to="/glossario">Glossário</Link><Link to="/cases">Cases</Link></div><button onClick={() => window.dispatchEvent(new Event("open-lucinari-chat"))} className="hidden rounded-full border border-[#c7a45b] px-4 py-2 font-outfit text-[10px] font-bold uppercase tracking-wider text-[#e2c88c] lg:block">Falar com especialista</button><button className="lg:hidden" onClick={() => setOpen(!open)} aria-label="Abrir menu">{open ? <X/> : <Menu/>}</button></nav>{open && <div className="border-t border-white/10 px-5 pb-5 text-center font-outfit text-xs uppercase tracking-wider lg:hidden"><Link className="block py-3" to="/solucoes/governanca-gestao-projetos">Produtos</Link><Link className="block py-3" to="/sobre">Sobre</Link><Link className="block py-3" to="/blog">Blog</Link><Link className="block py-3" to="/conhecimentos">Conhecimentos</Link><Link className="block py-3" to="/glossario">Glossário</Link><Link className="block py-3" to="/cases">Cases</Link></div>}</header>;
};

export const Footer = () => <footer className="mt-auto border-t border-white/10 bg-[#123c38] px-6 py-9 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 md:flex-row"><div><p className="font-fraunces text-2xl">lucinari<span className="text-[#e2c88c]">.</span></p><p className="mt-2 max-w-xs text-sm text-white/60">Método claro para decisões, cadência e entrega de valor.</p></div><div className="grid grid-cols-2 gap-10 text-sm text-white/70"><div><p className="mb-3 font-outfit text-[10px] font-bold uppercase tracking-widest text-[#e2c88c]">Conteúdo</p><Link className="block py-1" to="/blog">Blog</Link><Link className="block py-1" to="/conhecimentos">Conhecimentos</Link><Link className="block py-1" to="/glossario">Glossário</Link><Link className="block py-1" to="/cases">Cases</Link></div><div><p className="mb-3 font-outfit text-[10px] font-bold uppercase tracking-widest text-[#e2c88c]">Contato</p><a className="block py-1" href="https://wa.me/5511994706023">+55 11 99470-6023</a><a className="block py-1" href="mailto:lucinariconsulting@gmail.com">E-mail</a></div></div></div></footer>;
