import { ChevronDown, Menu, X } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";

export const Header = () => {
  const [open, setOpen] = useState(false);
  const [products, setProducts] = useState(false);
  return <header className="sticky top-0 z-40 border-b border-white/10 bg-[#0e302e]/95 text-white backdrop-blur"><nav className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link to="/" className="font-fraunces text-xl">lucinari<span className="text-[#e2c88c]">.</span><span className="ml-2 font-outfit text-[9px] uppercase tracking-[.2em] text-white/60">consulting</span></Link><div className="hidden items-center gap-6 font-outfit text-[10px] font-semibold uppercase tracking-[.12em] text-white/75 lg:flex"><div className="relative"><button onClick={() => setProducts(!products)} className="flex items-center gap-1 hover:text-[#e2c88c]">Produtos <ChevronDown size={14}/></button>{products && <div className="absolute left-0 top-7 w-60 rounded-2xl border border-white/10 bg-[#123c38] p-2 shadow-xl"><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/solucoes/governanca-pmo">Governança & PMO</Link><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/solucoes/vmo-valor">VMO & Valor</Link><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/solucoes/educacao-executiva">Educação Executiva</Link><Link className="block rounded-xl px-4 py-3 hover:bg-white/10" to="/treinamentos/governanca-estrategica-okrs">Treinamentos</Link></div>}</div><Link to="/blog">Blog</Link><Link to="/conhecimentos">Conhecimentos</Link><Link to="/glossario">Glossário</Link><Link to="/cases">Cases</Link></div><button onClick={() => window.dispatchEvent(new Event("open-lucinari-chat"))} className="hidden rounded-full border border-[#c7a45b] px-4 py-2 font-outfit text-[10px] font-bold uppercase tracking-wider text-[#e2c88c] lg:block">Falar com especialista</button><button className="lg:hidden" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></nav>{open && <div className="border-t border-white/10 px-5 pb-5 text-center font-outfit text-xs uppercase tracking-wider lg:hidden"><Link className="block py-3" to="/blog">Blog</Link><Link className="block py-3" to="/conhecimentos">Conhecimentos</Link><Link className="block py-3" to="/glossario">Glossário</Link><Link className="block py-3" to="/cases">Cases</Link></div>}</header>;
};

export const Footer = () => <footer className="mt-auto border-t border-white/10 bg-[#123c38] px-6 py-9 text-white lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 md:flex-row"><div><p className="font-fraunces text-2xl">lucinari<span className="text-[#e2c88c]">.</span></p><p className="mt-2 max-w-xs text-sm text-white/60">Método claro para decisões, cadência e entrega de valor.</p></div><div className="grid grid-cols-2 gap-10 text-sm text-white/70"><div><p className="mb-3 font-outfit text-[10px] font-bold uppercase tracking-widest text-[#e2c88c]">Conteúdo</p><Link className="block py-1" to="/blog">Blog</Link><Link className="block py-1" to="/conhecimentos">Conhecimentos</Link><Link className="block py-1" to="/glossario">Glossário</Link></div><div><p className="mb-3 font-outfit text-[10px] font-bold uppercase tracking-widest text-[#e2c88c]">Contato</p><a className="block py-1" href="https://wa.me/5511994706023">+55 11 99470-6023</a><a className="block py-1" href="mailto:lucinariconsulting@gmail.com">E-mail</a></div></div></div></footer>;
